typedef enum _JoypadType {
    kJoypadNone = 0,
    kJoypadDigital = 1,
    kJoypadAnalog = 2,
    kJoypadDualShock = 3,
    kJoypadMidi = 4,
    kJoypadXboxHxGuitar = 5,
    kJoypadXboxHxGuitarRb2 = 6,
    kJoypadXboxRoGuitar = 7,
    kJoypadXboxDrums = 8,
    kJoypadXboxDrumsRb2 = 9,
    kJoypadXboxRoDrums = 10,
    kJoypadXboxStageKit = 11,
    kJoypadPs3HxGuitar = 12,
    kJoypadPs3HxGuitarRb2 = 13,
    kJoypadPs3HxDrums = 14,
    kJoypadPs3HxDrumsRb2 = 15,
    kJoypadPs3RoGuitar = 16,
    kJoypadPs3RoDrums = 17,
    kJoypadPs3KonamiDrums = 18,
    kJoypadXboxCoreGuitar = 19,
    kJoypadXboxButtonGuitar = 20,
    kJoypadXboxRealGuitar22Fret = 21,
    kJoypadXboxMidiBoxKeyboard = 22,
    kJoypadXboxMidiBoxDrums = 23,
    kJoypadXboxKeytar = 24,
    kJoypadPs3CoreGuitar = 25,
    kJoypadPs3ButtonGuitar = 26,
    kJoypadPs3RealGuitar22Fret = 27,
    kJoypadPs3MidiBoxKeyboard = 28,
    kJoypadPs3MidiBoxDrums = 29,
    kJoypadPs3Keytar = 30,
    kJoypadPs4PembrokeGuitar = 31,
    kJoypadPs4PDPPembrokeGuitar = 32,
    kJoypadXb1PembrokeGuitar = 33,
    kJoypadXb1PDPPembrokeGuitar = 34,
    kJoypadGlamorganDrums = 35,
    kJoypadTouchDevice = 36,
    kJoypadOculusTouch = 37,
    kJoypadXboxDrumsRb2Usb = 38,
    kJoypadSwitchController = 39,
    kJoypadNumTypes = 40
} JoypadType;

typedef enum _LagContext {
    kGame = 0,
    kVCal = 1,
    kACal = 2,
    kNumLagContexts = 3
} LagContext;